### ISSUE TITLE
Invalid API Key responce from CoinbaseExchange.AuthenticatedClient

### ISSUE THREAD

**Issue by jtegtmeier** [coinbase/coinbase-exchange-node#47] opened 2016-06-03 04:23 UTC
Hello,

I can only get `{message: 'Invalid API Key'}` from the `authClient.getOrders()` response body for some reason.
The returned status code is `400`

Generated and copied the API key from [gdax.com/settings](https://www.gdax.com/settings) into:

``` javascript
var authClient = new CoinbaseExchange.AuthenticatedClient(key, b64secret, passphrase)
```

My callback code looks like this:

``` javascript
authClient.getOrders(function(err, response, data){
    if(err){
      console.log("Error getting orders:", err);
    }
    else{
      console.log("statusCode: ", response.statusCode);
      console.log(data);
    }
  });
```

Public methods are working fine, such as `authClient.getProductOrderBook()`.

Any ideas why this is? Am I missing something? From your [docs](https://docs.gdax.com/?javascript#requests) it shows that the statusCode should be 401 not 400 for this type of response.

Thanks!

**Comment by mihar** [comment] 2016-06-03 17:37
Hi @jtegtmeier, the response you're getting means we can't find the API key you specified in our records. So please double check you copied all the required fields correctly.

**Comment by jtegtmeier** [comment] 2016-06-03 17:48
Thanks for the reply!

I tried to re-generate the key / secret with a new passphase a few times with no luck. Also tried creating the http request myself following the NodeJS code example [here](https://docs.gdax.com/#signing-a-message) using the GET method, url https://api.gdax.com/orders, and leaving out the body (because I am requesting all orders), but get the same response.

I am copying the key exactly how i see it on your site. One thing I noticed is that the Coinbase API will email me when I create a key but the gdax API does not. Is this correct behavior?

**Comment by kpetrow** [comment] 2017-06-02 22:09
I am having the same issue with gdax api key.  How long does it take to activate the api key?  Is there a different response if the secret key is wrong?

also is there a sandbox key to use?

**Comment by rgrativol** [comment] 2017-07-22 22:32
Same issue here. Any answer?

**Comment by hanbingsy** [comment] 2017-11-07 21:31
Not sure you guys are still interested this problem or you already find out the answer or switched to another API but on my side, I got the same reject too. 

After tried to generate some keys, I noticed that only when I typed my own passphrase, the key can be used as a valid one. I don't know why the page fill the passphrase with a random string, maybe it is GDAX bug?

**Comment by btilford** [comment] 2017-11-09 01:59
Anyone? Do I just need to wait or is something wrong?

**Comment by Tokap** [comment] 2017-11-14 17:32
I encountered the same issues described above. I had instantiated one key with a custom password and when that seemed to fail, tried creating a key using the pre-generated password. Both instances led to the `Invalid API Key` error. 

Based on the suggestion made by @hanbingsy, I nuked both and tried once again with another custom password. I received the same error. HOWEVER, after 15 minutes or so the key worked perfectly fine. I think this might all have been a matter of impatience - at least on my end. Hoping this saves some people some frustration in the future.

**Comment by hanbingsy** [comment] 2017-11-15 21:35
Another small annoying design, you will be able to see your key in the API page IIF you have a valid key. Otherwise, you won't see anything.

**Comment by enginaar** [comment] 2018-01-28 17:12
I'm having the same issue with sandbox only, it's been more than an hour and I'm still waiting.

**Comment by imatFin** [comment] 2018-02-11 16:48
I am trying a basic API read call from a web app that consistently returns Key invalid error on my Coinbase key. I haven't tried typing the key out manually as suggested above but at the same time I did not copy paste it directly from the web page either, I used notepad. I have recreated the Coinbase API key over the past 3 weeks multiple times but the key invalid error remains the output in the webapp. I have contacted Coinbase but they will not deal with any tickets right now that are not a financial impact on their customers.

**Comment by BondWong** [comment] 2018-02-14 06:02
same issue, no luck with typing my own passphrase. Pro connection works fine for me but not sandbox. Gonna wait for a while and see.

**Comment by BondWong** [comment] 2018-02-14 06:39
ok it works.

**Comment by rmm5t** [comment] 2018-05-12 21:38
Just performing some triage and cleaning up some old issues and pull-requests. Because this repository was deprecated (and will not receive any further updates) in favor of [coinbase/gdax-node](https://github.com/coinbase/gdax-node), if this issue is still something you'd like to see addressed and it is still an issue on gdax-node, we would appreciate you closing this out in favor of starting a discussion at [coinbase/gdax-node](https://github.com/coinbase/gdax-node).

**Comment by imatFin** [comment] 2018-05-13 13:15
hello, the problem is somewhat solved. The data is imported but I still
receive invalid key error.

**Comment by uttamraj143** [comment] 2018-08-27 08:53
Is this issue solve I am getting same error when I tried from honeywell console it self.

**Comment by ghter111** [comment] 2018-09-26 02:18
you need to create a sandbox api key for the sandbox at 
 https://public.sandbox.pro.coinbase.com/profile/api

**Comment by drewrothstein** [comment] 2020-01-19 22:13
Hi, we are closing out PRs + Issues as this project is being archived.

**Closed as completed by drewrothstein** 2020-01-19 22:13 UTC
